# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ruoheng/ddb/easyDDB

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ruoheng/ddb/easyDDB

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ruoheng/ddb/easyDDB/CMakeFiles /home/ruoheng/ddb/easyDDB//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ruoheng/ddb/easyDDB/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named build_SQLParser

# Build rule for target.
build_SQLParser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_SQLParser
.PHONY : build_SQLParser

# fast build rule for target.
build_SQLParser/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build_SQLParser.dir/build.make CMakeFiles/build_SQLParser.dir/build
.PHONY : build_SQLParser/fast

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named db

# Build rule for target.
db: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 db
.PHONY : db

# fast build rule for target.
db/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/db.dir/build.make CMakeFiles/db.dir/build
.PHONY : db/fast

db.pb.o: db.pb.cc.o
.PHONY : db.pb.o

# target to build an object file
db.pb.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/db.pb.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/db.dir/build.make CMakeFiles/db.dir/db.pb.cc.o
.PHONY : db.pb.cc.o

db.pb.i: db.pb.cc.i
.PHONY : db.pb.i

# target to preprocess a source file
db.pb.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/db.pb.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/db.dir/build.make CMakeFiles/db.dir/db.pb.cc.i
.PHONY : db.pb.cc.i

db.pb.s: db.pb.cc.s
.PHONY : db.pb.s

# target to generate assembly for a file
db.pb.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/db.pb.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/db.dir/build.make CMakeFiles/db.dir/db.pb.cc.s
.PHONY : db.pb.cc.s

src/client/cli.o: src/client/cli.cpp.o
.PHONY : src/client/cli.o

# target to build an object file
src/client/cli.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/cli.cpp.o
.PHONY : src/client/cli.cpp.o

src/client/cli.i: src/client/cli.cpp.i
.PHONY : src/client/cli.i

# target to preprocess a source file
src/client/cli.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/cli.cpp.i
.PHONY : src/client/cli.cpp.i

src/client/cli.s: src/client/cli.cpp.s
.PHONY : src/client/cli.s

# target to generate assembly for a file
src/client/cli.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/cli.cpp.s
.PHONY : src/client/cli.cpp.s

src/client/client.o: src/client/client.cpp.o
.PHONY : src/client/client.o

# target to build an object file
src/client/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client.cpp.o
.PHONY : src/client/client.cpp.o

src/client/client.i: src/client/client.cpp.i
.PHONY : src/client/client.i

# target to preprocess a source file
src/client/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client.cpp.i
.PHONY : src/client/client.cpp.i

src/client/client.s: src/client/client.cpp.s
.PHONY : src/client/client.s

# target to generate assembly for a file
src/client/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client.cpp.s
.PHONY : src/client/client.cpp.s

src/db_server/aug_plan_executor.o: src/db_server/aug_plan_executor.cpp.o
.PHONY : src/db_server/aug_plan_executor.o

# target to build an object file
src/db_server/aug_plan_executor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/db.dir/build.make CMakeFiles/db.dir/src/db_server/aug_plan_executor.cpp.o
.PHONY : src/db_server/aug_plan_executor.cpp.o

src/db_server/aug_plan_executor.i: src/db_server/aug_plan_executor.cpp.i
.PHONY : src/db_server/aug_plan_executor.i

# target to preprocess a source file
src/db_server/aug_plan_executor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/db.dir/build.make CMakeFiles/db.dir/src/db_server/aug_plan_executor.cpp.i
.PHONY : src/db_server/aug_plan_executor.cpp.i

src/db_server/aug_plan_executor.s: src/db_server/aug_plan_executor.cpp.s
.PHONY : src/db_server/aug_plan_executor.s

# target to generate assembly for a file
src/db_server/aug_plan_executor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/db.dir/build.make CMakeFiles/db.dir/src/db_server/aug_plan_executor.cpp.s
.PHONY : src/db_server/aug_plan_executor.cpp.s

src/db_server/aug_planner.o: src/db_server/aug_planner.cpp.o
.PHONY : src/db_server/aug_planner.o

# target to build an object file
src/db_server/aug_planner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/db.dir/build.make CMakeFiles/db.dir/src/db_server/aug_planner.cpp.o
.PHONY : src/db_server/aug_planner.cpp.o

src/db_server/aug_planner.i: src/db_server/aug_planner.cpp.i
.PHONY : src/db_server/aug_planner.i

# target to preprocess a source file
src/db_server/aug_planner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/db.dir/build.make CMakeFiles/db.dir/src/db_server/aug_planner.cpp.i
.PHONY : src/db_server/aug_planner.cpp.i

src/db_server/aug_planner.s: src/db_server/aug_planner.cpp.s
.PHONY : src/db_server/aug_planner.s

# target to generate assembly for a file
src/db_server/aug_planner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/db.dir/build.make CMakeFiles/db.dir/src/db_server/aug_planner.cpp.s
.PHONY : src/db_server/aug_planner.cpp.s

src/db_server/cluster_manager.o: src/db_server/cluster_manager.cpp.o
.PHONY : src/db_server/cluster_manager.o

# target to build an object file
src/db_server/cluster_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/db.dir/build.make CMakeFiles/db.dir/src/db_server/cluster_manager.cpp.o
.PHONY : src/db_server/cluster_manager.cpp.o

src/db_server/cluster_manager.i: src/db_server/cluster_manager.cpp.i
.PHONY : src/db_server/cluster_manager.i

# target to preprocess a source file
src/db_server/cluster_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/db.dir/build.make CMakeFiles/db.dir/src/db_server/cluster_manager.cpp.i
.PHONY : src/db_server/cluster_manager.cpp.i

src/db_server/cluster_manager.s: src/db_server/cluster_manager.cpp.s
.PHONY : src/db_server/cluster_manager.s

# target to generate assembly for a file
src/db_server/cluster_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/db.dir/build.make CMakeFiles/db.dir/src/db_server/cluster_manager.cpp.s
.PHONY : src/db_server/cluster_manager.cpp.s

src/db_server/db.o: src/db_server/db.cpp.o
.PHONY : src/db_server/db.o

# target to build an object file
src/db_server/db.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/db.dir/build.make CMakeFiles/db.dir/src/db_server/db.cpp.o
.PHONY : src/db_server/db.cpp.o

src/db_server/db.i: src/db_server/db.cpp.i
.PHONY : src/db_server/db.i

# target to preprocess a source file
src/db_server/db.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/db.dir/build.make CMakeFiles/db.dir/src/db_server/db.cpp.i
.PHONY : src/db_server/db.cpp.i

src/db_server/db.s: src/db_server/db.cpp.s
.PHONY : src/db_server/db.s

# target to generate assembly for a file
src/db_server/db.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/db.dir/build.make CMakeFiles/db.dir/src/db_server/db.cpp.s
.PHONY : src/db_server/db.cpp.s

src/db_server/query_optimizer.o: src/db_server/query_optimizer.cpp.o
.PHONY : src/db_server/query_optimizer.o

# target to build an object file
src/db_server/query_optimizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/db.dir/build.make CMakeFiles/db.dir/src/db_server/query_optimizer.cpp.o
.PHONY : src/db_server/query_optimizer.cpp.o

src/db_server/query_optimizer.i: src/db_server/query_optimizer.cpp.i
.PHONY : src/db_server/query_optimizer.i

# target to preprocess a source file
src/db_server/query_optimizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/db.dir/build.make CMakeFiles/db.dir/src/db_server/query_optimizer.cpp.i
.PHONY : src/db_server/query_optimizer.cpp.i

src/db_server/query_optimizer.s: src/db_server/query_optimizer.cpp.s
.PHONY : src/db_server/query_optimizer.s

# target to generate assembly for a file
src/db_server/query_optimizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/db.dir/build.make CMakeFiles/db.dir/src/db_server/query_optimizer.cpp.s
.PHONY : src/db_server/query_optimizer.cpp.s

src/db_server/site_task_executor.o: src/db_server/site_task_executor.cpp.o
.PHONY : src/db_server/site_task_executor.o

# target to build an object file
src/db_server/site_task_executor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/db.dir/build.make CMakeFiles/db.dir/src/db_server/site_task_executor.cpp.o
.PHONY : src/db_server/site_task_executor.cpp.o

src/db_server/site_task_executor.i: src/db_server/site_task_executor.cpp.i
.PHONY : src/db_server/site_task_executor.i

# target to preprocess a source file
src/db_server/site_task_executor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/db.dir/build.make CMakeFiles/db.dir/src/db_server/site_task_executor.cpp.i
.PHONY : src/db_server/site_task_executor.cpp.i

src/db_server/site_task_executor.s: src/db_server/site_task_executor.cpp.s
.PHONY : src/db_server/site_task_executor.s

# target to generate assembly for a file
src/db_server/site_task_executor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/db.dir/build.make CMakeFiles/db.dir/src/db_server/site_task_executor.cpp.s
.PHONY : src/db_server/site_task_executor.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... build_SQLParser"
	@echo "... client"
	@echo "... db"
	@echo "... db.pb.o"
	@echo "... db.pb.i"
	@echo "... db.pb.s"
	@echo "... src/client/cli.o"
	@echo "... src/client/cli.i"
	@echo "... src/client/cli.s"
	@echo "... src/client/client.o"
	@echo "... src/client/client.i"
	@echo "... src/client/client.s"
	@echo "... src/db_server/aug_plan_executor.o"
	@echo "... src/db_server/aug_plan_executor.i"
	@echo "... src/db_server/aug_plan_executor.s"
	@echo "... src/db_server/aug_planner.o"
	@echo "... src/db_server/aug_planner.i"
	@echo "... src/db_server/aug_planner.s"
	@echo "... src/db_server/cluster_manager.o"
	@echo "... src/db_server/cluster_manager.i"
	@echo "... src/db_server/cluster_manager.s"
	@echo "... src/db_server/db.o"
	@echo "... src/db_server/db.i"
	@echo "... src/db_server/db.s"
	@echo "... src/db_server/query_optimizer.o"
	@echo "... src/db_server/query_optimizer.i"
	@echo "... src/db_server/query_optimizer.s"
	@echo "... src/db_server/site_task_executor.o"
	@echo "... src/db_server/site_task_executor.i"
	@echo "... src/db_server/site_task_executor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

